name: make check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install EVM assembler
        run: git clone --depth 1 --revision ce7ad588c737f2d11d3f8b55ec427a611a540c2f --recurse-submodules --shallow-submodules --no-tags https://github.com/wjmelements/evm.git

      - name: Build EVM assembler
        run: make -C evm check

      - name: Install EVM assembler
        run: sudo install $(pwd)/evm/bin/evm $(dirname $(which git))/evm

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.5.1
          cache: true

      - name: make test
        run: make test

      - name: forge fmt
        run: forge fmt --check
